<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="5" hostname="DESKTOP-6JHQO45" name="com.retry.Test1" tests="8" failures="0" timestamp="2020-04-11T15:05:35 EDT" time="0.022" errors="1">
  <testcase name="secondTest" time="0.002" classname="com.retry.Test1">
    <skipped/>
  </testcase> <!-- secondTest -->
  <system-out/>
  <testcase name="secondTest" time="0.001" classname="com.retry.Test1">
    <skipped/>
  </testcase> <!-- secondTest -->
  <system-out/>
  <testcase name="secondTest" time="0.002" classname="com.retry.Test1">
    <skipped/>
  </testcase> <!-- secondTest -->
  <system-out/>
  <testcase name="secondTest" time="0.002" classname="com.retry.Test1">
    <skipped/>
  </testcase> <!-- secondTest -->
  <system-out/>
  <testcase name="secondTest" time="0.002" classname="com.retry.Test1">
    <error type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
at com.retry.Test1.secondTest(Test1.java:18)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- secondTest -->
  <system-out/>
  <testcase name="firstTest" time="0.010" classname="com.retry.Test1"/>
  <system-out/>
  <testcase name="test" time="0.002" classname="com.retry.Test1"/>
  <system-out/>
  <testcase name="secondTest" time="0.001" classname="com.retry.Test1">
    <skipped/>
  </testcase> <!-- secondTest -->
  <system-out/>
</testsuite> <!-- com.retry.Test1 -->
